In [7]:
import numpy as np

In [3]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1.shape)

(2, 3)


In [5]:
arr1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
arr1.shape

(3, 4)

In [13]:
arr2=np.array([[1,2],[1,2],[1,2]])
arr2.shape

(3, 2)

In [15]:
arr1

array([[1, 2],
       [1, 2],
       [1, 2]])

In [11]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2


array([[1, 2],
       [1, 2],
       [1, 2]])

In [19]:
arr1

array([[1, 2],
       [1, 2],
       [1, 2]])

In [23]:
arr3=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
arr3.shape

(3, 4)

In [27]:
arr3.shape=(4,3)

In [29]:
arr3

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4]])

In [31]:
arr3.size


12

In [33]:
arr1.size

6

In [37]:
arr2.size

6

In [39]:
arr4=np.zeros((3,2))
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
arr5=np.zeros((3,2),dtype=int)
arr5


array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
arr7=np.ones((3,2),dtype=int)
arr7


array([[1, 1],
       [1, 1],
       [1, 1]])

In [47]:
arr7.shape=(2,3)
arr7

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
#3d array 3,4,5
arr8=np.array([[[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[4,4,4,4],[5,5,5,5],[6,6,6,6]]])
arr8.shape

(2, 3, 4)

In [57]:
arr8


array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])

In [61]:
arr9=np.arange(2,11,2)
arr9

array([ 2,  4,  6,  8, 10])

In [63]:
arr10=np.arange(1,10,2)
arr10

array([1, 3, 5, 7, 9])

In [65]:
arr11=np.arange(1,10,0.5)
arr11

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [67]:
arr12=np.array([[21,45,79],[54,34,23],[56,66,19]])
arr12
               

array([[21, 45, 79],
       [54, 34, 23],
       [56, 66, 19]])

In [69]:
np.amin(arr12,1)

array([21, 23, 19])

In [73]:
np.amax(arr12,1)  #rows

array([79, 54, 66])

In [75]:
np.amin(arr12,0)  #columns

array([21, 34, 19])

In [77]:
np.amax(arr12,0)

array([56, 66, 79])

In [79]:
arr13=np.array([1,2,3,4,5])
arr13


array([1, 2, 3, 4, 5])

In [81]:
np.mean(arr13)

3.0

In [83]:
arr14=np.array([[1,2,4],[2,6,7]])
arr14

array([[1, 2, 4],
       [2, 6, 7]])

In [85]:
np.mean(arr14)

3.6666666666666665

In [87]:
np.median(arr14)

3.0

In [91]:
np.average(arr14)

3.6666666666666665

In [93]:
np.var(arr14)


4.888888888888889

In [95]:
np.std(arr14)

2.211083193570267

In [107]:
arr15=np.array([[1,2,3],[5,6,7],[9,10,11],[12,13,14]])# numpy methods
print(arr15.shape)
print(arr15)
print(np.average(arr15))
print(np.mean(arr15))
print(np.median(arr15))
print(np.var(arr15))
print(np.std(arr15))
print(np.amin(arr15,1))
print(np.amin(arr15,0))
print(np.amax(arr15,1))
print(np.amax(arr15,0))
print(np.amax(arr15))
print(np.amin(arr15))

(4, 3)
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]]
7.75
7.75
8.0
17.854166666666668
4.225419111362406
[ 1  5  9 12]
[1 2 3]
[ 3  7 11 14]
[12 13 14]
14
1


In [119]:
#arithmetic operators
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
print("a1:",a1)
print("a2:",a2)
print("additon of 2 array is:\n",a1+a2)
print("subraction of 2 array is:\n",a1-a2)
print("division of 2 array is:\n",a1/a2)
print("multiplication of 2 array is:\n",a1*a2)
print("matrix multiplication of 2 array is:\n",a1@a2)
print("matrix multiplication of 2 array is:\n",a1.dot(a2))
print("transpose of a matrix :\n",a1.transpose())
print("transpose of a matrix :\n",a2.transpose())

a1: [[1 1]
 [2 2]]
a2: [[3 3]
 [4 4]]
additon of 2 array is:
 [[4 4]
 [6 6]]
subraction of 2 array is:
 [[-2 -2]
 [-2 -2]]
division of 2 array is:
 [[0.33333333 0.33333333]
 [0.5        0.5       ]]
multiplication of 2 array is:
 [[3 3]
 [8 8]]
matrix multiplication of 2 array is:
 [[ 7  7]
 [14 14]]
matrix multiplication of 2 array is:
 [[ 7  7]
 [14 14]]
transpose of a matrix :
 [[1 2]
 [1 2]]
transpose of a matrix :
 [[3 4]
 [3 4]]


In [11]:
arr17=np.arange(1,21,1)
arr17

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
print(arr17[11:15])

[12 13 14 15]


In [15]:
import pandas as pd

In [19]:
data=[11,12,13,14]
s=pd.Series(data)
print(s)

0    11
1    12
2    13
3    14
dtype: int64


In [21]:
data=[11,12.9,13,14]
c=pd.Series(data)
print(c)

0    11.0
1    12.9
2    13.0
3    14.0
dtype: float64


In [51]:
#data frame
dict={'Name':['a','b','c','d','e','f','g','h','i'],'Roll No':[10,20,30,40,50,60,70,80,90],'Age':[17,18,19,20,21,22,23,24,25]}
print(dict)

{'Name': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], 'Roll No': [10, 20, 30, 40, 50, 60, 70, 80, 90], 'Age': [17, 18, 19, 20, 21, 22, 23, 24, 25]}


In [53]:
df=pd.DataFrame(dict)
df

Name  Roll No  Age
0    a       10   17
1    b       20   18
2    c       30   19
3    d       40   20
4    e       50   21
5    f       60   22
6    g       70   23
7    h       80   24
8    i       90   25

In [55]:
df.head()#first 5rows

Name  Roll No  Age
0    a       10   17
1    b       20   18
2    c       30   19
3    d       40   20
4    e       50   21

In [59]:
df.tail()  #last 5 rows

Name  Roll No  Age
4    e       50   21
5    f       60   22
6    g       70   23
7    h       80   24
8    i       90   25

In [61]:
df.head(3)

Name  Roll No  Age
0    a       10   17
1    b       20   18
2    c       30   19

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     9 non-null      object
 1   Roll No  9 non-null      int64 
 2   Age      9 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 348.0+ bytes


In [71]:
df.describe()

Roll No        Age
count   9.000000   9.000000
mean   50.000000  21.000000
std    27.386128   2.738613
min    10.000000  17.000000
25%    30.000000  19.000000
50%    50.000000  21.000000
75%    70.000000  23.000000
max    90.000000  25.000000

In [77]:
df['Name'] #single column

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
Name: Name, dtype: object

In [75]:
df['Age']

0    17
1    18
2    19
3    20
4    21
5    22
6    23
7    24
8    25
Name: Age, dtype: int64

In [81]:
df[['Name','Age']]#multiple column

Name  Age
0    a   17
1    b   18
2    c   19
3    d   20
4    e   21
5    f   22
6    g   23
7    h   24
8    i   25

In [87]:
df.loc[0]

Name        a
Roll No    10
Age        17
Name: 0, dtype: object

In [89]:
df.iloc[0]

Name        a
Roll No    10
Age        17
Name: 0, dtype: object

In [91]:
# filtering data
df[df['Age']>20]


Name  Roll No  Age
4    e       50   21
5    f       60   22
6    g       70   23
7    h       80   24
8    i       90   25

In [93]:
df[df['Age']==18]

Name  Roll No  Age
1    b       20   18

In [95]:
# modifying data
df['Age']=df['Age']+2
df

Name  Roll No  Age
0    a       10   19
1    b       20   20
2    c       30   21
3    d       40   22
4    e       50   23
5    f       60   24
6    g       70   25
7    h       80   26
8    i       90   27

In [97]:
df['Age']=df['Age']-2
df

Name  Roll No  Age
0    a       10   17
1    b       20   18
2    c       30   19
3    d       40   20
4    e       50   21
5    f       60   22
6    g       70   23
7    h       80   24
8    i       90   25

In [111]:
# handlingmissing data
import numpy as np
dict1={'Name':['a','b','c','d','e','f','g','h','i'],'Roll No':[10,20,30,40,None,60,70,80,90],'Age':[17,18,19,20,21,22,23,24,25]}
df=pd.DataFrame(dict1)
df

Name  Roll No  Age
0    a     10.0   17
1    b     20.0   18
2    c     30.0   19
3    d     40.0   20
4    e      NaN   21
5    f     60.0   22
6    g     70.0   23
7    h     80.0   24
8    i     90.0   25

In [121]:
df.dropna()# dropping row which having missing data

Name  Roll No  Age
0    a     10.0   17
1    b     20.0   18
2    c     30.0   19
3    d     40.0   20
5    f     60.0   22
6    g     70.0   23
7    h     80.0   24
8    i     90.0   25

In [123]:
df.fillna(1)# filling the missing data

Name  Roll No  Age
0    a     10.0   17
1    b     20.0   18
2    c     30.0   19
3    d     40.0   20
4    e      1.0   21
5    f     60.0   22
6    g     70.0   23
7    h     80.0   24
8    i     90.0   25

In [125]:
#Sorting
df.sort_values(by='Roll No')

Name  Roll No  Age
0    a     10.0   17
1    b     20.0   18
2    c     30.0   19
3    d     40.0   20
5    f     60.0   22
6    g     70.0   23
7    h     80.0   24
8    i     90.0   25
4    e      NaN   21

In [127]:
df.sort_values('Age')

Name  Roll No  Age
0    a     10.0   17
1    b     20.0   18
2    c     30.0   19
3    d     40.0   20
4    e      NaN   21
5    f     60.0   22
6    g     70.0   23
7    h     80.0   24
8    i     90.0   25

In [131]:
# add an other column
df['Marks']=[50,90,80,70,98,67,54,90,68]
df

Name  Roll No  Age  Marks
0    a     10.0   17     50
1    b     20.0   18     90
2    c     30.0   19     80
3    d     40.0   20     70
4    e      NaN   21     98
5    f     60.0   22     67
6    g     70.0   23     54
7    h     80.0   24     90
8    i     90.0   25     68